/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AlertUi {
    }
    interface BadgeUi {
    }
    interface DividerUi {
        "size": string;
        "variant": 'solid' | 'dashed';
    }
    interface IndicatorUi {
    }
    interface SkeletonUi {
        "cols": number;
        "height": number;
        "rows": number;
        "space": number;
    }
}
declare global {
    interface HTMLAlertUiElement extends Components.AlertUi, HTMLStencilElement {
    }
    var HTMLAlertUiElement: {
        prototype: HTMLAlertUiElement;
        new (): HTMLAlertUiElement;
    };
    interface HTMLBadgeUiElement extends Components.BadgeUi, HTMLStencilElement {
    }
    var HTMLBadgeUiElement: {
        prototype: HTMLBadgeUiElement;
        new (): HTMLBadgeUiElement;
    };
    interface HTMLDividerUiElement extends Components.DividerUi, HTMLStencilElement {
    }
    var HTMLDividerUiElement: {
        prototype: HTMLDividerUiElement;
        new (): HTMLDividerUiElement;
    };
    interface HTMLIndicatorUiElement extends Components.IndicatorUi, HTMLStencilElement {
    }
    var HTMLIndicatorUiElement: {
        prototype: HTMLIndicatorUiElement;
        new (): HTMLIndicatorUiElement;
    };
    interface HTMLSkeletonUiElement extends Components.SkeletonUi, HTMLStencilElement {
    }
    var HTMLSkeletonUiElement: {
        prototype: HTMLSkeletonUiElement;
        new (): HTMLSkeletonUiElement;
    };
    interface HTMLElementTagNameMap {
        "alert-ui": HTMLAlertUiElement;
        "badge-ui": HTMLBadgeUiElement;
        "divider-ui": HTMLDividerUiElement;
        "indicator-ui": HTMLIndicatorUiElement;
        "skeleton-ui": HTMLSkeletonUiElement;
    }
}
declare namespace LocalJSX {
    interface AlertUi {
    }
    interface BadgeUi {
    }
    interface DividerUi {
        "size"?: string;
        "variant"?: 'solid' | 'dashed';
    }
    interface IndicatorUi {
    }
    interface SkeletonUi {
        "cols"?: number;
        "height"?: number;
        "rows"?: number;
        "space"?: number;
    }
    interface IntrinsicElements {
        "alert-ui": AlertUi;
        "badge-ui": BadgeUi;
        "divider-ui": DividerUi;
        "indicator-ui": IndicatorUi;
        "skeleton-ui": SkeletonUi;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "alert-ui": LocalJSX.AlertUi & JSXBase.HTMLAttributes<HTMLAlertUiElement>;
            "badge-ui": LocalJSX.BadgeUi & JSXBase.HTMLAttributes<HTMLBadgeUiElement>;
            "divider-ui": LocalJSX.DividerUi & JSXBase.HTMLAttributes<HTMLDividerUiElement>;
            "indicator-ui": LocalJSX.IndicatorUi & JSXBase.HTMLAttributes<HTMLIndicatorUiElement>;
            "skeleton-ui": LocalJSX.SkeletonUi & JSXBase.HTMLAttributes<HTMLSkeletonUiElement>;
        }
    }
}
