/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AlertUi {
        "addRole": boolean;
        "colorScheme": | 'whiteAlpha'
		| 'blackAlpha'
		| 'gray'
		| 'red'
		| 'orange'
		| 'yellow'
		| 'green'
		| 'teal'
		| 'blue'
		| 'cyan'
		| 'purple'
		| 'pink';
        "fullWidth": boolean;
        "size": 'sm' | 'md' | 'lg';
        "status": 'info' | 'warning' | 'success' | 'error' | 'loading';
        "variant": 'subtle' | 'left-accent' | 'top-accent' | 'solid';
    }
    interface BadgeUi {
        "colorScheme": 'default' | 'dark' | 'red' | 'green' | 'yellow' | 'indigo' | 'purple' | 'pink';
        "size": 'xs' | 'sm' | 'md' | 'lg' | 'xl';
        "text": string;
        "variant": 'solid' | 'subtle' | 'outline';
    }
    interface ButtonUi {
        "gradient": string;
    }
    interface DividerUi {
        "size": string;
        "variant": 'solid' | 'dashed';
    }
    interface IndicatorUi {
        "background": boolean;
        "color": 'blue' | 'green' | 'red' | 'yellow' | 'indigo' | 'purple' | 'pink';
        "text": string;
    }
    interface SkeletonUi {
        "cols": number;
        "height": number;
        "rows": number;
        "space": number;
    }
}
export interface ButtonUiCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLButtonUiElement;
}
declare global {
    interface HTMLAlertUiElement extends Components.AlertUi, HTMLStencilElement {
    }
    var HTMLAlertUiElement: {
        prototype: HTMLAlertUiElement;
        new (): HTMLAlertUiElement;
    };
    interface HTMLBadgeUiElement extends Components.BadgeUi, HTMLStencilElement {
    }
    var HTMLBadgeUiElement: {
        prototype: HTMLBadgeUiElement;
        new (): HTMLBadgeUiElement;
    };
    interface HTMLButtonUiElementEventMap {
        "onClick": void;
    }
    interface HTMLButtonUiElement extends Components.ButtonUi, HTMLStencilElement {
        addEventListener<K extends keyof HTMLButtonUiElementEventMap>(type: K, listener: (this: HTMLButtonUiElement, ev: ButtonUiCustomEvent<HTMLButtonUiElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLButtonUiElementEventMap>(type: K, listener: (this: HTMLButtonUiElement, ev: ButtonUiCustomEvent<HTMLButtonUiElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLButtonUiElement: {
        prototype: HTMLButtonUiElement;
        new (): HTMLButtonUiElement;
    };
    interface HTMLDividerUiElement extends Components.DividerUi, HTMLStencilElement {
    }
    var HTMLDividerUiElement: {
        prototype: HTMLDividerUiElement;
        new (): HTMLDividerUiElement;
    };
    interface HTMLIndicatorUiElement extends Components.IndicatorUi, HTMLStencilElement {
    }
    var HTMLIndicatorUiElement: {
        prototype: HTMLIndicatorUiElement;
        new (): HTMLIndicatorUiElement;
    };
    interface HTMLSkeletonUiElement extends Components.SkeletonUi, HTMLStencilElement {
    }
    var HTMLSkeletonUiElement: {
        prototype: HTMLSkeletonUiElement;
        new (): HTMLSkeletonUiElement;
    };
    interface HTMLElementTagNameMap {
        "alert-ui": HTMLAlertUiElement;
        "badge-ui": HTMLBadgeUiElement;
        "button-ui": HTMLButtonUiElement;
        "divider-ui": HTMLDividerUiElement;
        "indicator-ui": HTMLIndicatorUiElement;
        "skeleton-ui": HTMLSkeletonUiElement;
    }
}
declare namespace LocalJSX {
    interface AlertUi {
        "addRole"?: boolean;
        "colorScheme"?: | 'whiteAlpha'
		| 'blackAlpha'
		| 'gray'
		| 'red'
		| 'orange'
		| 'yellow'
		| 'green'
		| 'teal'
		| 'blue'
		| 'cyan'
		| 'purple'
		| 'pink';
        "fullWidth"?: boolean;
        "size"?: 'sm' | 'md' | 'lg';
        "status"?: 'info' | 'warning' | 'success' | 'error' | 'loading';
        "variant"?: 'subtle' | 'left-accent' | 'top-accent' | 'solid';
    }
    interface BadgeUi {
        "colorScheme"?: 'default' | 'dark' | 'red' | 'green' | 'yellow' | 'indigo' | 'purple' | 'pink';
        "size"?: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
        "text"?: string;
        "variant"?: 'solid' | 'subtle' | 'outline';
    }
    interface ButtonUi {
        "gradient"?: string;
        "onOnClick"?: (event: ButtonUiCustomEvent<void>) => void;
    }
    interface DividerUi {
        "size"?: string;
        "variant"?: 'solid' | 'dashed';
    }
    interface IndicatorUi {
        "background"?: boolean;
        "color"?: 'blue' | 'green' | 'red' | 'yellow' | 'indigo' | 'purple' | 'pink';
        "text"?: string;
    }
    interface SkeletonUi {
        "cols"?: number;
        "height"?: number;
        "rows"?: number;
        "space"?: number;
    }
    interface IntrinsicElements {
        "alert-ui": AlertUi;
        "badge-ui": BadgeUi;
        "button-ui": ButtonUi;
        "divider-ui": DividerUi;
        "indicator-ui": IndicatorUi;
        "skeleton-ui": SkeletonUi;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "alert-ui": LocalJSX.AlertUi & JSXBase.HTMLAttributes<HTMLAlertUiElement>;
            "badge-ui": LocalJSX.BadgeUi & JSXBase.HTMLAttributes<HTMLBadgeUiElement>;
            "button-ui": LocalJSX.ButtonUi & JSXBase.HTMLAttributes<HTMLButtonUiElement>;
            "divider-ui": LocalJSX.DividerUi & JSXBase.HTMLAttributes<HTMLDividerUiElement>;
            "indicator-ui": LocalJSX.IndicatorUi & JSXBase.HTMLAttributes<HTMLIndicatorUiElement>;
            "skeleton-ui": LocalJSX.SkeletonUi & JSXBase.HTMLAttributes<HTMLSkeletonUiElement>;
        }
    }
}
