/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DividerUi {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface SkeletonUi {
        "cols": number;
        "height": number;
        "loading": boolean;
        "rows": number;
        "space": number;
    }
}
declare global {
    interface HTMLDividerUiElement extends Components.DividerUi, HTMLStencilElement {
    }
    var HTMLDividerUiElement: {
        prototype: HTMLDividerUiElement;
        new (): HTMLDividerUiElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLSkeletonUiElement extends Components.SkeletonUi, HTMLStencilElement {
    }
    var HTMLSkeletonUiElement: {
        prototype: HTMLSkeletonUiElement;
        new (): HTMLSkeletonUiElement;
    };
    interface HTMLElementTagNameMap {
        "divider-ui": HTMLDividerUiElement;
        "my-component": HTMLMyComponentElement;
        "skeleton-ui": HTMLSkeletonUiElement;
    }
}
declare namespace LocalJSX {
    interface DividerUi {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface SkeletonUi {
        "cols"?: number;
        "height"?: number;
        "loading"?: boolean;
        "rows"?: number;
        "space"?: number;
    }
    interface IntrinsicElements {
        "divider-ui": DividerUi;
        "my-component": MyComponent;
        "skeleton-ui": SkeletonUi;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "divider-ui": LocalJSX.DividerUi & JSXBase.HTMLAttributes<HTMLDividerUiElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "skeleton-ui": LocalJSX.SkeletonUi & JSXBase.HTMLAttributes<HTMLSkeletonUiElement>;
        }
    }
}
